### ISSUE TITLE
SQL Error while runing your first example

### ISSUE THREAD

**Issue by mlifemaker** [ecoron/SerpScrap#12]
While rununing your first example:
import serpscrap

keywords = ['one', 'two']
scrap = serpscrap.SerpScrap()
scrap.init(keywords=keywords)
result = scrap.scrap_serps()
I get this error:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: 'SELECT scraper_search.id AS scraper_search_id, scraper_search.keyword_file AS scraper_search_keyword_file, scraper_search.number_search_engines_used AS scraper_search_number_search_engines_used, scraper_search.used_search_engines AS scraper_search_used_search_engines, scraper_search.number_proxies_used AS scraper_search_number_proxies_used, scraper_search.number_search_queries AS scraper_search_number_search_queries, scraper_search.started_searching AS scraper_search_started_searching \nFROM scraper_search \nWHERE scraper_search.id = ?'] [parameters: (6,)]

How can I fix it? should install a SQL database and configure it first?

**Comment by ecoron** [comment]
Hi, it seems to be a permission issue. By default SQLight is used. The database is created automatically in the /tmp dir. Can you check if the executing user has write permissions on it. Or can you provide some more information about your environment?

**Comment by mlifemaker** [comment]
Hi, 
Some times it works and sometimes I get this error. I think the connection is lost to SQLite. maybe should do a retry to connect when you insert data to SQL.

**Comment by ecoron** [comment]
OK, thx for reporting. I will investigate to make this stable.

**Comment by rohini0** [comment]
i m facing similar issue.
