### ISSUE TITLE
Element not visible

### ISSUE THREAD

**Issue by xjuric29** [ecoron/SerpScrap#15]
Hi, I'm using your python module for finding keywords from database (I have some information about companies without theirs url - roughly 2k?) but after some time of finding I get selenium.common.exceptions.ElementNotVisibleException: Message: element not visible error. I'm using Chrome for scraping. This means that I have many googledriver running process which do not end. Google blocked me or is there another fault?

And I find two small bugs which are already in GoogleScraper:
- Selenium gecko driver process never end, there is some quit error
- Google Chrome in selenium mode doesn't start by root (needed --no-sandbox option)

**Comment by ecoron** [comment]
Hi, THX for reporting. I will check it next time.
