### ISSUE TITLE
How to use with different languages and countries?

### ISSUE THREAD

**Issue by fbaeumer** [ecoron/SerpScrap#23]
By default the script uses google.com and English as far as I see. How can I configure the script to use German for example and google.de or google.cz?

**Comment by ecoron** [comment]
Hi, first you can try it with an custom header "Accept-Language" see example in http://serpscrap.readthedocs.io/en/latest/configuration.html#headers

Or you can try a custom search url (which is not documented and fully tested yet of corse)
`config.set('google_search_url', 'https://www.google.com/search?')`
