### ISSUE TITLE
100 results from google search

### ISSUE THREAD

**Issue by tobyhage** [ecoron/SerpScrap#30]
Hello,

First thank you for this nice software :-).

I think i have found two issues. The first one is that i don't get 100 results from google search.

I have set following config options:

config.set('num_pages_for_keyword', 1)
config.set('num_results_per_page', 100)

But i get 10 results back instead of 100.

Is this a known issue or do i miss something....

I will post the other issue i have found in another post.

kind regards,

Toby.

**Comment by bernardosrulzon** [comment]
@tobyhage Try this workaround:

```
config.set('google_search_url', 'https://www.google.com.br/search?num=100')
```

**Comment by tobyhage** [comment]
Thank you, this is working :-)

**Comment by ecoron** [comment]
@bernardosrulzon thx for sharing. i try to find some time to work on this project again.

**Comment by ecoron** [comment]
starting in 0.10.3 you can also just use the config key 'num_results_per_page'
`config.set('num_results_per_page', 100)`
