### ISSUE TITLE
keyerror: Using your own configuration

### ISSUE THREAD

**Issue by tobyhage** [ecoron/SerpScrap#31]
Hello,

Here my second issue i have found.

regarding: http://serpscrap.readthedocs.io/en/latest/configuration.html
i can use own configuration. This is not working for me. I get error:

KeyError: 'executable_path'

i have solved this by adding a executable path, but then i get other keyerrors.

For the moment i have set all options so that there are no more keyerrors. But now i get:

scrapcore.scraper.selenium - ERROR - Message: Service /home/ubuntu/workspace/wp-content/themes/SerpScrap/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs unexpectedly exited. Status code was: 0

Exception in thread [google]SelScrape

So what can i do?

regards,

Toby.

**Comment by fassn** [comment]
Not a direct answer to your question, but since phantomjs developement has been discontinued. I'd rather use chrome with its headless feature.
I hope this workaround can solve your problem.
