### ISSUE TITLE
Similar Text_Raw field for all search results

### ISSUE THREAD

**Issue by MNCTTY** [ecoron/SerpScrap#36]
Hello! 

Thank you for great utility!
Faced with some problem:
I need to get the whole text from the search results, the snippet is too small for my issue,
 so I thought that **text_raw** is a field for that. But for every result it's filled with the same text, and I can't understand why is that. 
[SerpScrap.ipynb.zip](https://github.com/ecoron/SerpScrap/files/2276968/SerpScrap.ipynb.zip)

I attached my notebook with results.

Thank you in advance for your answer

**Comment by ecoron** [comment]
Basicly it was created to store the raw text of scraped webpages. i think this part isn't working well yet but i will come back to make it stable again.

**Comment by ecoron** [comment]
i'm on it. will be part of version 0.11.0

**Comment by ecoron** [comment]
fetching the raw text content of urls was updated in 0.11.0 and should work now. see https://serpscrap.readthedocs.io/en/latest/examples.html#example-serp-results-and-raw-text-of-result-urls 
 and https://serpscrap.readthedocs.io/en/latest/results.html for more details.
