### ISSUE TITLE
Getting "People Also Ask" results as results

### ISSUE THREAD

**Issue by smithellis** [ecoron/SerpScrap#46]
Any way to dump those/filter those out?

**Comment by ecoron** [comment]
I think this is what you are looking for: https://github.com/ecoron/SerpScrap/blob/master/examples/example_related.py

**Comment by dogancanbaris** [comment]
Hey, I don't think that answers the questions. The results include people also asked for links as well and I need to filter those out. It should only give me the organic links without any from people also asked for. Could you please help?
